/*
 * Payment Processor Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.PaymentprocessorAvailabilityContext;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentprocessorListAvailablePaymentMethodsRequest
 */
public class PaymentprocessorListAvailablePaymentMethodsRequestTest {
    private final PaymentprocessorListAvailablePaymentMethodsRequest model = new PaymentprocessorListAvailablePaymentMethodsRequest();

    /**
     * Model tests for PaymentprocessorListAvailablePaymentMethodsRequest
     */
    @Test
    public void testPaymentprocessorListAvailablePaymentMethodsRequest() {
        // TODO: test PaymentprocessorListAvailablePaymentMethodsRequest
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'context'
     */
    @Test
    public void contextTest() {
        // TODO: test context
    }

    /**
     * Test the property 'authenticateMethods'
     */
    @Test
    public void authenticateMethodsTest() {
        // TODO: test authenticateMethods
    }

}
