/*
 * Payment Processor Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentprocessorGetPaymentMethodConfigurationResponse
 */
public class PaymentprocessorGetPaymentMethodConfigurationResponseTest {
    private final PaymentprocessorGetPaymentMethodConfigurationResponse model = new PaymentprocessorGetPaymentMethodConfigurationResponse();

    /**
     * Model tests for PaymentprocessorGetPaymentMethodConfigurationResponse
     */
    @Test
    public void testPaymentprocessorGetPaymentMethodConfigurationResponse() {
        // TODO: test PaymentprocessorGetPaymentMethodConfigurationResponse
    }

    /**
     * Test the property '_configuration'
     */
    @Test
    public void _configurationTest() {
        // TODO: test _configuration
    }

}
