/*
 * Payment Processor Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.PaymentprocessorAvailabilityContext;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentprocessorGetAvailablePaymentMethodRequest
 */
public class PaymentprocessorGetAvailablePaymentMethodRequestTest {
    private final PaymentprocessorGetAvailablePaymentMethodRequest model = new PaymentprocessorGetAvailablePaymentMethodRequest();

    /**
     * Model tests for PaymentprocessorGetAvailablePaymentMethodRequest
     */
    @Test
    public void testPaymentprocessorGetAvailablePaymentMethodRequest() {
        // TODO: test PaymentprocessorGetAvailablePaymentMethodRequest
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'context'
     */
    @Test
    public void contextTest() {
        // TODO: test context
    }

    /**
     * Test the property 'authenticateMethod'
     */
    @Test
    public void authenticateMethodTest() {
        // TODO: test authenticateMethod
    }

}
