/*
 * Payment Processor Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ConditionAction;
import org.openapitools.client.model.PaymentMethodRestrictionConditionCondition;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentprocessorPaymentMethodRestrictionCondition
 */
public class PaymentprocessorPaymentMethodRestrictionConditionTest {
    private final PaymentprocessorPaymentMethodRestrictionCondition model = new PaymentprocessorPaymentMethodRestrictionCondition();

    /**
     * Model tests for PaymentprocessorPaymentMethodRestrictionCondition
     */
    @Test
    public void testPaymentprocessorPaymentMethodRestrictionCondition() {
        // TODO: test PaymentprocessorPaymentMethodRestrictionCondition
    }

    /**
     * Test the property 'contextPath'
     */
    @Test
    public void contextPathTest() {
        // TODO: test contextPath
    }

    /**
     * Test the property 'action'
     */
    @Test
    public void actionTest() {
        // TODO: test action
    }

    /**
     * Test the property 'condition'
     */
    @Test
    public void conditionTest() {
        // TODO: test condition
    }

    /**
     * Test the property 'values'
     */
    @Test
    public void valuesTest() {
        // TODO: test values
    }

}
